# Generated by Django 3.1.5 on 2021-02-07 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_delete_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='restaurant_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.restaurant'),
        ),
    ]
