# Generated by Django 3.1.5 on 2021-02-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_food_restaurant_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='restaurant_id',
            new_name='restaurant',
        ),
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
