# Generated by Django 3.1.5 on 2021-02-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_delete_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='owner_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
