# Generated by Django 3.1.5 on 2021-02-16 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_order_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_id',
            new_name='order_counter',
        ),
    ]
