# Generated by Django 3.1.5 on 2021-03-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_auto_20210309_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='close_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='open_time',
            field=models.TimeField(null=True),
        ),
    ]
